import { z } from 'zod'
import { api } from '../../lib/apiClient'

// System IDs are strings (e.g. "system_1784296376035"). Numeric-looking fields
// come back as strings from mysql2, so coerce where we need numbers.
export const systemSchema = z.object({
  id: z.string(),
  system_name: z.string(),
  system_type: z.string().nullable().optional(),
  fish_tank_count: z.coerce.number().nullable().optional(),
  grow_bed_count: z.coerce.number().nullable().optional(),
  total_grow_area: z.coerce.number().nullable().optional(),
  // Present only on the list endpoint. shared_permission is null for owned
  // systems; is_owner is 1/0.
  shared_permission: z.string().nullable().optional(),
  is_owner: z.coerce.number().nullable().optional(),
  // The farm this system belongs to (an owned system's farm is one of the user's
  // own farms; a shared system carries its owner's farm id).
  farm_id: z.string().nullable().optional(),
  // JSON array of metric keys this system tracks; null = track everything.
  tracked_metrics: z.string().nullable().optional(),
})
export type System = z.infer<typeof systemSchema>

// The owner sees is_owner=1 / shared_permission=null. A shared system has a
// permission level and is_owner=0.
export function isOwnedSystem(s: System | null | undefined): boolean {
  if (!s) return false
  if (s.is_owner != null) return s.is_owner === 1
  return s.shared_permission == null
}

// Whether the current user can modify this system's data.
export function canWriteSystem(s: System | null | undefined): boolean {
  return isOwnedSystem(s) || s?.shared_permission === 'collaborator' || s?.shared_permission === 'admin'
}

export async function fetchSystems(): Promise<System[]> {
  const data = await api<unknown[]>('/systems')
  return z.array(systemSchema).parse(data)
}

// Create a system. The id is generated by the backend (a random UUID) and
// returned on the created row, so it must be read from the response rather
// than chosen here. Defaults are filled in server-side for anything omitted.
export async function createSystem(input: {
  system_name: string
  farm_id?: string
  system_type?: string
  fish_type?: string
  fish_tank_count?: number
  grow_bed_count?: number
  total_grow_area?: number
}): Promise<string> {
  const created = await api<unknown>('/systems', {
    method: 'POST',
    body: { ...input, system_name: input.system_name.trim() },
  })
  return systemSchema.pick({ id: true }).parse(created).id
}

// Update a system's editable fields. The backend only touches the fields
// present in the body and scopes the update by owner.
export async function updateSystem(id: string, input: { system_name?: string; system_type?: string }) {
  const body = { ...input, ...(input.system_name != null ? { system_name: input.system_name.trim() } : {}) }
  return api(`/systems/${id}`, { method: 'PUT', body })
}

// Permanently delete a system and all its data (cascades server-side).
export async function deleteSystem(id: string) {
  return api(`/systems/${id}`, { method: 'DELETE' })
}

// Set which water/nutrient metrics this system tracks (owner-only server-side).
export async function updateTrackedMetrics(id: string, metrics: string[]) {
  return api(`/systems/${id}/metrics`, { method: 'PUT', body: { metrics } })
}

// Add a fish tank to a system (used by the creation wizard).
export function createFishTank(systemId: string, tank: { tank_number: number; volume_liters: number; fish_type: string }) {
  return api('/fish-tanks', {
    method: 'POST',
    body: {
      system_id: systemId,
      tank_number: tank.tank_number,
      size_m3: tank.volume_liters / 1000,
      volume_liters: tank.volume_liters,
      fish_type: tank.fish_type,
    },
  })
}

// Bulk-save the grow beds for a system (the endpoint upserts and computes
// equivalent_m2). Used by the creation wizard.
export function saveGrowBedsBulk(systemId: string, growBeds: unknown[]) {
  return api(`/grow-beds/system/${systemId}`, { method: 'POST', body: { growBeds } })
}

// Import a full demo system (in its own "Demo Farm") for the current user.
// Returns the created system + farm ids so the app can switch straight to it.
export async function createDemoSystem(name: string): Promise<{ systemId: string; farmId: string | null }> {
  const data = await api<{ id?: string; farm_id?: string | null }>('/systems/create-demo', { method: 'POST', body: { system_name: name.trim() } })
  return { systemId: data?.id ?? '', farmId: data?.farm_id ?? null }
}
